while True:
    if input.light_level() > 30:
     music.beat(200)
     music.set_volume(255)
    music.play_melody("C# C# E D# B B C# C# E D# B", 200)
    music.play_melody("G E F# D# E C# D# B", 200)
    music.play_melody("G E F# D# E D# C# B", 200)
    music.play_melody("B5 G A F# G E F# D#", 200)
    music.play_melody("B5 G A F# G F# E D#", 200)
    music.play_melody("B C# A# B G# A# F#", 200)
    music.play_melody("D# B C# A# B A# G# F#", 200)
    music.play_melody("D# B C# A# B G# A# F#", 200)
    music.play_melody("D# B C# A# B G# A# F#", 200)
    music.play_melody("D# B C# A# B G# A# F#", 200)
    music.play_melody("D# B C# A# B G# A# F#", 200)
    music.play_melody("D# B C# A# B G# A# F#", 200)
    music.play_melody("D# B C# A# B A# G# G", 200)
    music.play_melody("G# G# G# G# A# B A# G# G", 200)
    music.play_melody("G G G# G# A A#", 200)
    music.play_melody("A A# B A# B C", 200)
    music.play_melody("C# C# C# C# A C#", 200)
    music.play_melody("B B B G# B", 200)
    music.play_melody("C# C# C# C# A C# C# C# C# C C", 200)
    music.play_melody("C# C# E D# B C# C# E D# B", 200)
    music.play_melody("C# C# E D# B C# C# B G# B", 200)
    music.play_melody("C# C# E D# B C# C# E D# B", 200)
    music.play_melody("C# C# E D# B B C# G# F#", 200)
    music.play_melody("C# C# E D# B C# C# E D# B", 200)
    music.play_melody("C# C# E D# C# C# B G# B", 200)
    music.play_melody("C# C# E D# B C# C# E D# B", 200)
    music.play_melody("C# E D# C# B C#", 200)
    music.play_melody("G# E F# D# E C# D# B", 200)
    music.play_melody("G# E F# D# E D# C# B", 200)
    music.play_melody("B G# A F# G# E F# D#", 200)
    music.play_melody("B G# A F# G# F# E D#", 200)
    music.play_melody("B G# A F# G# E F# D#", 200)
    music.play_melody("B G# A F# G# F# E D#", 200)
    music.play_melody("D A# C A A# G A F", 200)
    music.play_melody("D A# C A A#", 200)
    music.play_melody("G", 200)
    music.stop_all_sounds()   