while (true) {
    if (input.lightLevel() > 30) {
        music.beat(200)
        music.setVolume(255)
    }
    
    music.playMelody("C# C# E D# B B C# C# E D# B", 200)
    music.playMelody("G E F# D# E C# D# B", 200)
    music.playMelody("G E F# D# E D# C# B", 200)
    music.playMelody("B5 G A F# G E F# D#", 200)
    music.playMelody("B5 G A F# G F# E D#", 200)
    music.playMelody("B C# A# B G# A# F#", 200)
    music.playMelody("D# B C# A# B A# G# F#", 200)
    music.playMelody("D# B C# A# B G# A# F#", 200)
    music.playMelody("D# B C# A# B G# A# F#", 200)
    music.playMelody("D# B C# A# B G# A# F#", 200)
    music.playMelody("D# B C# A# B G# A# F#", 200)
    music.playMelody("D# B C# A# B G# A# F#", 200)
    music.playMelody("D# B C# A# B A# G# G", 200)
    music.playMelody("G# G# G# G# A# B A# G# G", 200)
    music.playMelody("G G G# G# A A#", 200)
    music.playMelody("A A# B A# B C", 200)
    music.playMelody("C# C# C# C# A C#", 200)
    music.playMelody("B B B G# B", 200)
    music.playMelody("C# C# C# C# A C# C# C# C# C C", 200)
    music.playMelody("C# C# E D# B C# C# E D# B", 200)
    music.playMelody("C# C# E D# B C# C# B G# B", 200)
    music.playMelody("C# C# E D# B C# C# E D# B", 200)
    music.playMelody("C# C# E D# B B C# G# F#", 200)
    music.playMelody("C# C# E D# B C# C# E D# B", 200)
    music.playMelody("C# C# E D# C# C# B G# B", 200)
    music.playMelody("C# C# E D# B C# C# E D# B", 200)
    music.playMelody("C# E D# C# B C#", 200)
    music.playMelody("G# E F# D# E C# D# B", 200)
    music.playMelody("G# E F# D# E D# C# B", 200)
    music.playMelody("B G# A F# G# E F# D#", 200)
    music.playMelody("B G# A F# G# F# E D#", 200)
    music.playMelody("B G# A F# G# E F# D#", 200)
    music.playMelody("B G# A F# G# F# E D#", 200)
    music.playMelody("D A# C A A# G A F", 200)
    music.playMelody("D A# C A A#", 200)
    music.playMelody("G", 200)
    music.stopAllSounds()
}
